databases:
  - name: MausiBud
    databaseName: mausibud
    user: mausibud_user

services:
  - type: web
    name: MausiBud
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false